const axios = require('axios')

const artistsData = {
    items: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1XpDYCrUJnvCo9Ez6yeMWh'
        },
        followers: {
          href: null,
          total: 1092585
        },
        genres: [
          'alternative metal',
          'comedy rock',
          'comic',
          'comic metal',
          'parody',
          'post-grunge',
          'rock'
        ],
        href: 'https://api.spotify.com/v1/artists/1XpDYCrUJnvCo9Ez6yeMWh',
        id: '1XpDYCrUJnvCo9Ez6yeMWh',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/945d649ebebd1804ecbca36de5e304fc2da0854b',
            width: 640
          },
          {
            height: 320,
            url: 'https://i.scdn.co/image/ae7f4739d5202488330ee544d3b10ed67c6a3904',
            width: 320
          },
          {
            height: 160,
            url: 'https://i.scdn.co/image/532447f1aef5e2269750d70667bfefe0b03443b0',
            width: 160
          }
        ],
        name: 'Tenacious D',
        popularity: 66,
        type: 'artist',
        uri: 'spotify:artist:1XpDYCrUJnvCo9Ez6yeMWh'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/6l3HvQ5sa6mXTsMTB19rO5'
        },
        followers: {
          href: null,
          total: 10625505
        },
        genres: [
          'conscious hip hop',
          'hip hop',
          'nc hip hop',
          'pop rap',
          'rap'
        ],
        href: 'https://api.spotify.com/v1/artists/6l3HvQ5sa6mXTsMTB19rO5',
        id: '6l3HvQ5sa6mXTsMTB19rO5',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/1e9eeefb2c94579150fc37916e8319b975ec8a52',
            width: 640
          },
          {
            height: 320,
            url: 'https://i.scdn.co/image/e021db512f24f1b9aafad580db7408863346e9cf',
            width: 320
          },
          {
            height: 160,
            url: 'https://i.scdn.co/image/35c726dfde2a3d5545a8b6cbe9cfeaaea3666764',
            width: 160
          }
        ],
        name: 'J. Cole',
        popularity: 87,
        type: 'artist',
        uri: 'spotify:artist:6l3HvQ5sa6mXTsMTB19rO5'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg'
        },
        followers: {
          href: null,
          total: 14345247
        },
        genres: [
          'conscious hip hop',
          'hip hop',
          'rap',
          'west coast rap'
        ],
        href: 'https://api.spotify.com/v1/artists/2YZyLoL8N0Wb9xBt1NhZWg',
        id: '2YZyLoL8N0Wb9xBt1NhZWg',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/3a836196bfb341f736c7fe2704fb75de53f8dfbb',
            width: 640
          },
          {
            height: 320,
            url: 'https://i.scdn.co/image/5259c0496329b3f608a1ae0edb799cd2f8451acc',
            width: 320
          },
          {
            height: 160,
            url: 'https://i.scdn.co/image/b772a78d4cb192268d6f601a78f21044c17d6dda',
            width: 160
          }
        ],
        name: 'Kendrick Lamar',
        popularity: 87,
        type: 'artist',
        uri: 'spotify:artist:2YZyLoL8N0Wb9xBt1NhZWg'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/7hJcb9fa4alzcOq3EaNPoG'
        },
        followers: {
          href: null,
          total: 5693265
        },
        genres: [
          'g funk',
          'gangster rap',
          'hip hop',
          'pop rap',
          'rap',
          'west coast rap'
        ],
        href: 'https://api.spotify.com/v1/artists/7hJcb9fa4alzcOq3EaNPoG',
        id: '7hJcb9fa4alzcOq3EaNPoG',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/11208d65843456cf3854717b8e411ef8fede7141',
            width: 640
          },
          {
            height: 320,
            url: 'https://i.scdn.co/image/4ddba58867285a1e858291a108613526df2ce934',
            width: 320
          },
          {
            height: 160,
            url: 'https://i.scdn.co/image/1e67815be9174e75753d52a006b86077a39719cf',
            width: 160
          }
        ],
        name: 'Snoop Dogg',
        popularity: 83,
        type: 'artist',
        uri: 'spotify:artist:7hJcb9fa4alzcOq3EaNPoG'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/45Yz90pqjzEdJzpEQg1eII'
        },
        followers: {
          href: null,
          total: 614385
        },
        genres: [
          'brazilian hip hop',
          'trap brasileiro'
        ],
        href: 'https://api.spotify.com/v1/artists/45Yz90pqjzEdJzpEQg1eII',
        id: '45Yz90pqjzEdJzpEQg1eII',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/11b9dd1f955ea92020269ff55b0bf393218e52cf',
            width: 640
          },
          {
            height: 320,
            url: 'https://i.scdn.co/image/11cf937737c454a94994af6a8f61e63c92e75218',
            width: 320
          },
          {
            height: 160,
            url: 'https://i.scdn.co/image/6c3e6b28d7adb8d9be6bd9bd6a058320f06c347f',
            width: 160
          }
        ],
        name: 'Froid',
        popularity: 69,
        type: 'artist',
        uri: 'spotify:artist:45Yz90pqjzEdJzpEQg1eII'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR'
        },
        followers: {
          href: null,
          total: 34124509
        },
        genres: [
          'detroit hip hop',
          'g funk',
          'hip hop',
          'rap'
        ],
        href: 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR',
        id: '7dGJo4pcD2V6oG8kP0tJRR',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/56f4762485066b4ef867b96e16775f2b5b4db277',
            width: 640
          },
          {
            height: 320,
            url: 'https://i.scdn.co/image/ad64a7fbc24b31cd84455a1aef34758b94246352',
            width: 320
          },
          {
            height: 160,
            url: 'https://i.scdn.co/image/6432e1be8495593f136ad98de6135bb0640ff936',
            width: 160
          }
        ],
        name: 'Eminem',
        popularity: 94,
        type: 'artist',
        uri: 'spotify:artist:7dGJo4pcD2V6oG8kP0tJRR'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/3q7HBObVc0L8jNeTe5Gofh'
        },
        followers: {
          href: null,
          total: 5947237
        },
        genres: [
          'east coast hip hop',
          'gangster rap',
          'hip hop',
          'pop rap',
          'queens hip hop',
          'rap'
        ],
        href: 'https://api.spotify.com/v1/artists/3q7HBObVc0L8jNeTe5Gofh',
        id: '3q7HBObVc0L8jNeTe5Gofh',
        images: [
          {
            height: 977,
            url: 'https://i.scdn.co/image/dd031b9c5d1b6eba4a691cd89c954255aae787f2',
            width: 781
          },
          {
            height: 801,
            url: 'https://i.scdn.co/image/6f0da41419b31d9d2ba55d2df212f59ad0668118',
            width: 640
          },
          {
            height: 250,
            url: 'https://i.scdn.co/image/df73c0cebe56cafe705ffdba5085ccbd5680bd16',
            width: 200
          },
          {
            height: 80,
            url: 'https://i.scdn.co/image/1a44043542c997ef835c89e185f0cf79d7402153',
            width: 64
          }
        ],
        name: '50 Cent',
        popularity: 82,
        type: 'artist',
        uri: 'spotify:artist:3q7HBObVc0L8jNeTe5Gofh'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0IVBT8qQNwvHLzOJL6kGpE'
        },
        followers: {
          href: null,
          total: 1064707
        },
        genres: [
          'brazilian edm',
          'brazilian hip hop'
        ],
        href: 'https://api.spotify.com/v1/artists/0IVBT8qQNwvHLzOJL6kGpE',
        id: '0IVBT8qQNwvHLzOJL6kGpE',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/e52b04296fd7a70a5d32bb13bfffd0881da29ae7',
            width: 640
          },
          {
            height: 320,
            url: 'https://i.scdn.co/image/ef2ef299edb49e52c81268d79afda805a3ea2255',
            width: 320
          },
          {
            height: 160,
            url: 'https://i.scdn.co/image/8554a2125acdf5de3d455622a891141863fb5a41',
            width: 160
          }
        ],
        name: 'Oriente',
        popularity: 63,
        type: 'artist',
        uri: 'spotify:artist:0IVBT8qQNwvHLzOJL6kGpE'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/1ZwdS5xdxEREPySFridCfh'
        },
        followers: {
          href: null,
          total: 8062521
        },
        genres: [
          'g funk',
          'gangster rap',
          'hip hop',
          'rap',
          'west coast rap'
        ],
        href: 'https://api.spotify.com/v1/artists/1ZwdS5xdxEREPySFridCfh',
        id: '1ZwdS5xdxEREPySFridCfh',
        images: [
          {
            height: 1000,
            url: 'https://i.scdn.co/image/fdb2382075f400ca2f2fbddaebb93add82ca8f32',
            width: 1000
          },
          {
            height: 640,
            url: 'https://i.scdn.co/image/e92cf49011e4c26f736cd479b0b64cb08f1b52c6',
            width: 640
          },
          {
            height: 200,
            url: 'https://i.scdn.co/image/0334d2f0cd1eb65f81831c4ddf4a0b249479564c',
            width: 200
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/c9baaaa56cc3e4c1b5b60e09632ba8b78ff52abd',
            width: 64
          }
        ],
        name: '2Pac',
        popularity: 80,
        type: 'artist',
        uri: 'spotify:artist:1ZwdS5xdxEREPySFridCfh'
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9'
        },
        followers: {
          href: null,
          total: 11861860
        },
        genres: [
          'album rock',
          'art rock',
          'classic rock',
          'progressive rock',
          'psychedelic rock',
          'rock',
          'symphonic rock'
        ],
        href: 'https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE9',
        id: '0k17h0D3J5VfsdmQ1iZtE9',
        images: [
          {
            height: 977,
            url: 'https://i.scdn.co/image/e69f71e2be4b67b82af90fb8e9d805715e0684fa',
            width: 1000
          },
          {
            height: 625,
            url: 'https://i.scdn.co/image/d011c95081cd9a329e506abd7ded47535d524a07',
            width: 640
          },
          {
            height: 195,
            url: 'https://i.scdn.co/image/f0a39a8a196a87a7236bdcf8a8708f6d5d3547cc',
            width: 200
          },
          {
            height: 63,
            url: 'https://i.scdn.co/image/ec1fb7127168dbaa962404031409c5a293b95ec6',
            width: 64
          }
        ],
        name: 'Pink Floyd',
        popularity: 82,
        type: 'artist',
        uri: 'spotify:artist:0k17h0D3J5VfsdmQ1iZtE9'
      }
    ],
    total: 50,
    limit: 10,
    offset: 5,
    href: 'https://api.spotify.com/v1/me/top/artists?limit=10&offset=5',
    previous: null,
    next: 'https://api.spotify.com/v1/me/top/artists?limit=10&offset=15'
  }

  const tracksData = {
    items: [
      {
        album: {
          album_type: 'SINGLE',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/6USMTwO0MNDnKte5a5h0xx'
              },
              href: 'https://api.spotify.com/v1/artists/6USMTwO0MNDnKte5a5h0xx',
              id: '6USMTwO0MNDnKte5a5h0xx',
              name: 'Y2K',
              type: 'artist',
              uri: 'spotify:artist:6USMTwO0MNDnKte5a5h0xx'
            },
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/41X1TR6hrK8Q2ZCpp2EqCz'
              },
              href: 'https://api.spotify.com/v1/artists/41X1TR6hrK8Q2ZCpp2EqCz',
              id: '41X1TR6hrK8Q2ZCpp2EqCz',
              name: 'bbno$',
              type: 'artist',
              uri: 'spotify:artist:41X1TR6hrK8Q2ZCpp2EqCz'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/4WlC4FXhonJhNTXCQPGP3r'
          },
          href: 'https://api.spotify.com/v1/albums/4WlC4FXhonJhNTXCQPGP3r',
          id: '4WlC4FXhonJhNTXCQPGP3r',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b2738a6ccb507dd6a66f7f6e2440',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e028a6ccb507dd6a66f7f6e2440',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d000048518a6ccb507dd6a66f7f6e2440',
              width: 64
            }
          ],
          name: 'Lalala',
          release_date: '2019-06-28',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:4WlC4FXhonJhNTXCQPGP3r'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/6USMTwO0MNDnKte5a5h0xx'
            },
            href: 'https://api.spotify.com/v1/artists/6USMTwO0MNDnKte5a5h0xx',
            id: '6USMTwO0MNDnKte5a5h0xx',
            name: 'Y2K',
            type: 'artist',
            uri: 'spotify:artist:6USMTwO0MNDnKte5a5h0xx'
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/41X1TR6hrK8Q2ZCpp2EqCz'
            },
            href: 'https://api.spotify.com/v1/artists/41X1TR6hrK8Q2ZCpp2EqCz',
            id: '41X1TR6hrK8Q2ZCpp2EqCz',
            name: 'bbno$',
            type: 'artist',
            uri: 'spotify:artist:41X1TR6hrK8Q2ZCpp2EqCz'
          }
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 160626,
        explicit: true,
        external_ids: {
          isrc: 'USSM11904230'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/51Fjme0JiitpyXKuyQiCDo'
        },
        href: 'https://api.spotify.com/v1/tracks/51Fjme0JiitpyXKuyQiCDo',
        id: '51Fjme0JiitpyXKuyQiCDo',
        is_local: false,
        name: 'Lalala',
        popularity: 88,
        preview_url: 'https://p.scdn.co/mp3-preview/3fa108534da58a2782b9c60b1c3a2d0aa18fb451?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:51Fjme0JiitpyXKuyQiCDo'
      },
      {
        album: {
          album_type: 'SINGLE',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS'
              },
              href: 'https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS',
              id: '1z7b1Pr1rSlvWRzsW3HOrS',
              name: 'Russ',
              type: 'artist',
              uri: 'spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/3Gc9sZYGLxEbDfGShMeXOX'
          },
          href: 'https://api.spotify.com/v1/albums/3Gc9sZYGLxEbDfGShMeXOX',
          id: '3Gc9sZYGLxEbDfGShMeXOX',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b2731d313e2d3ea704a2a8f7d7bf',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e021d313e2d3ea704a2a8f7d7bf',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d000048511d313e2d3ea704a2a8f7d7bf',
              width: 64
            }
          ],
          name: 'Overdue',
          release_date: '2016-10-10',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:3Gc9sZYGLxEbDfGShMeXOX'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1z7b1Pr1rSlvWRzsW3HOrS'
            },
            href: 'https://api.spotify.com/v1/artists/1z7b1Pr1rSlvWRzsW3HOrS',
            id: '1z7b1Pr1rSlvWRzsW3HOrS',
            name: 'Russ',
            type: 'artist',
            uri: 'spotify:artist:1z7b1Pr1rSlvWRzsW3HOrS'
          }
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 215066,
        explicit: true,
        external_ids: {
          isrc: 'TCACS1658386'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/1Uh36HwT2nXXw1nF0OXa34'
        },
        href: 'https://api.spotify.com/v1/tracks/1Uh36HwT2nXXw1nF0OXa34',
        id: '1Uh36HwT2nXXw1nF0OXa34',
        is_local: false,
        name: 'Overdue',
        popularity: 55,
        preview_url: 'https://p.scdn.co/mp3-preview/fc9357d52a89560fadea6165b2255d8def1d055d?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:1Uh36HwT2nXXw1nF0OXa34'
      },
      {
        album: {
          album_type: 'ALBUM',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop'
              },
              href: 'https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop',
              id: '137W8MRPWKqSmrBGDBFSop',
              name: 'Wiz Khalifa',
              type: 'artist',
              uri: 'spotify:artist:137W8MRPWKqSmrBGDBFSop'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/2pl9PVgr8QFKRGY0HY69GI'
          },
          href: 'https://api.spotify.com/v1/albums/2pl9PVgr8QFKRGY0HY69GI',
          id: '2pl9PVgr8QFKRGY0HY69GI',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b27327ed4f26fa2bfbd714dba7dd',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e0227ed4f26fa2bfbd714dba7dd',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d0000485127ed4f26fa2bfbd714dba7dd',
              width: 64
            }
          ],
          name: 'Blacc Hollywood (Deluxe)',
          release_date: '2014-08-19',
          release_date_precision: 'day',
          total_tracks: 15,
          type: 'album',
          uri: 'spotify:album:2pl9PVgr8QFKRGY0HY69GI'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop'
            },
            href: 'https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop',
            id: '137W8MRPWKqSmrBGDBFSop',
            name: 'Wiz Khalifa',
            type: 'artist',
            uri: 'spotify:artist:137W8MRPWKqSmrBGDBFSop'
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4fQHCuys7JZvaQzRvB1kPR'
            },
            href: 'https://api.spotify.com/v1/artists/4fQHCuys7JZvaQzRvB1kPR',
            id: '4fQHCuys7JZvaQzRvB1kPR',
            name: 'Ghost Loft',
            type: 'artist',
            uri: 'spotify:artist:4fQHCuys7JZvaQzRvB1kPR'
          }
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 249287,
        explicit: true,
        external_ids: {
          isrc: 'USAT21402807'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/0odHj0qIf86vHBsXB30IkZ'
        },
        href: 'https://api.spotify.com/v1/tracks/0odHj0qIf86vHBsXB30IkZ',
        id: '0odHj0qIf86vHBsXB30IkZ',
        is_local: false,
        name: 'So High (feat. Ghost Loft)',
        popularity: 68,
        preview_url: 'https://p.scdn.co/mp3-preview/d03fe8c0132a2d4deb749e8f420f44a95c213458?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 10,
        type: 'track',
        uri: 'spotify:track:0odHj0qIf86vHBsXB30IkZ'
      },
      {
        album: {
          album_type: 'ALBUM',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/0Y5tJX1MQlPlqiwlOH1tJY'
              },
              href: 'https://api.spotify.com/v1/artists/0Y5tJX1MQlPlqiwlOH1tJY',
              id: '0Y5tJX1MQlPlqiwlOH1tJY',
              name: 'Travis Scott',
              type: 'artist',
              uri: 'spotify:artist:0Y5tJX1MQlPlqiwlOH1tJY'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/41GuZcammIkupMPKH2OJ6I'
          },
          href: 'https://api.spotify.com/v1/albums/41GuZcammIkupMPKH2OJ6I',
          id: '41GuZcammIkupMPKH2OJ6I',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273072e9faef2ef7b6db63834a3',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02072e9faef2ef7b6db63834a3',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851072e9faef2ef7b6db63834a3',
              width: 64
            }
          ],
          name: 'ASTROWORLD',
          release_date: '2018-08-03',
          release_date_precision: 'day',
          total_tracks: 17,
          type: 'album',
          uri: 'spotify:album:41GuZcammIkupMPKH2OJ6I'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0Y5tJX1MQlPlqiwlOH1tJY'
            },
            href: 'https://api.spotify.com/v1/artists/0Y5tJX1MQlPlqiwlOH1tJY',
            id: '0Y5tJX1MQlPlqiwlOH1tJY',
            name: 'Travis Scott',
            type: 'artist',
            uri: 'spotify:artist:0Y5tJX1MQlPlqiwlOH1tJY'
          }
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 190557,
        explicit: false,
        external_ids: {
          isrc: 'USSM11704799'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/2cYqizR4lgvp4Qu6IQ3qGN'
        },
        href: 'https://api.spotify.com/v1/tracks/2cYqizR4lgvp4Qu6IQ3qGN',
        id: '2cYqizR4lgvp4Qu6IQ3qGN',
        is_local: false,
        name: 'BUTTERFLY EFFECT',
        popularity: 81,
        preview_url: 'https://p.scdn.co/mp3-preview/ca4f131887eae894020e48ea809af1186c95f542?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 15,
        type: 'track',
        uri: 'spotify:track:2cYqizR4lgvp4Qu6IQ3qGN'
      },
      {
        album: {
          album_type: 'ALBUM',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/0Y5tJX1MQlPlqiwlOH1tJY'
              },
              href: 'https://api.spotify.com/v1/artists/0Y5tJX1MQlPlqiwlOH1tJY',
              id: '0Y5tJX1MQlPlqiwlOH1tJY',
              name: 'Travis Scott',
              type: 'artist',
              uri: 'spotify:artist:0Y5tJX1MQlPlqiwlOH1tJY'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/41GuZcammIkupMPKH2OJ6I'
          },
          href: 'https://api.spotify.com/v1/albums/41GuZcammIkupMPKH2OJ6I',
          id: '41GuZcammIkupMPKH2OJ6I',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273072e9faef2ef7b6db63834a3',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02072e9faef2ef7b6db63834a3',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851072e9faef2ef7b6db63834a3',
              width: 64
            }
          ],
          name: 'ASTROWORLD',
          release_date: '2018-08-03',
          release_date_precision: 'day',
          total_tracks: 17,
          type: 'album',
          uri: 'spotify:album:41GuZcammIkupMPKH2OJ6I'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0Y5tJX1MQlPlqiwlOH1tJY'
            },
            href: 'https://api.spotify.com/v1/artists/0Y5tJX1MQlPlqiwlOH1tJY',
            id: '0Y5tJX1MQlPlqiwlOH1tJY',
            name: 'Travis Scott',
            type: 'artist',
            uri: 'spotify:artist:0Y5tJX1MQlPlqiwlOH1tJY'
          }
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 312820,
        explicit: true,
        external_ids: {
          isrc: 'USSM11806660'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/2xLMifQCjDGFmkHkpNLD9h'
        },
        href: 'https://api.spotify.com/v1/tracks/2xLMifQCjDGFmkHkpNLD9h',
        id: '2xLMifQCjDGFmkHkpNLD9h',
        is_local: false,
        name: 'SICKO MODE',
        popularity: 86,
        preview_url: 'https://p.scdn.co/mp3-preview/1c3c01c64477b356e28a652b6447f4ef96689a71?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 3,
        type: 'track',
        uri: 'spotify:track:2xLMifQCjDGFmkHkpNLD9h'
      },
      {
        album: {
          album_type: 'ALBUM',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/7iZtZyCzp3LItcw1wtPI3D'
              },
              href: 'https://api.spotify.com/v1/artists/7iZtZyCzp3LItcw1wtPI3D',
              id: '7iZtZyCzp3LItcw1wtPI3D',
              name: 'Rae Sremmurd',
              type: 'artist',
              uri: 'spotify:artist:7iZtZyCzp3LItcw1wtPI3D'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/5v6iBhIlflzR9rEd1LAMbd'
          },
          href: 'https://api.spotify.com/v1/albums/5v6iBhIlflzR9rEd1LAMbd',
          id: '5v6iBhIlflzR9rEd1LAMbd',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273881fb62d913fe712fc2e1c95',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02881fb62d913fe712fc2e1c95',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851881fb62d913fe712fc2e1c95',
              width: 64
            }
          ],
          name: 'SremmLife 2 (Deluxe)',
          release_date: '2016-08-12',
          release_date_precision: 'day',
          total_tracks: 14,
          type: 'album',
          uri: 'spotify:album:5v6iBhIlflzR9rEd1LAMbd'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7iZtZyCzp3LItcw1wtPI3D'
            },
            href: 'https://api.spotify.com/v1/artists/7iZtZyCzp3LItcw1wtPI3D',
            id: '7iZtZyCzp3LItcw1wtPI3D',
            name: 'Rae Sremmurd',
            type: 'artist',
            uri: 'spotify:artist:7iZtZyCzp3LItcw1wtPI3D'
          }
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 228000,
        explicit: true,
        external_ids: {
          isrc: 'USUM71603292'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/2IGr3q6ljcpLvHDFLtI0yW'
        },
        href: 'https://api.spotify.com/v1/tracks/2IGr3q6ljcpLvHDFLtI0yW',
        id: '2IGr3q6ljcpLvHDFLtI0yW',
        is_local: false,
        name: 'Look Alive',
        popularity: 62,
        preview_url: 'https://p.scdn.co/mp3-preview/f80a256462ea14a50ce131d6526050761958abc2?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 4,
        type: 'track',
        uri: 'spotify:track:2IGr3q6ljcpLvHDFLtI0yW'
      },
      {
        album: {
          album_type: 'ALBUM',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/5OrB6Jhhrl9y2PK0pSV4VP'
              },
              href: 'https://api.spotify.com/v1/artists/5OrB6Jhhrl9y2PK0pSV4VP',
              id: '5OrB6Jhhrl9y2PK0pSV4VP',
              name: 'Young Money',
              type: 'artist',
              uri: 'spotify:artist:5OrB6Jhhrl9y2PK0pSV4VP'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/0UwpSCPnNPksM1meQJnBAF'
          },
          href: 'https://api.spotify.com/v1/albums/0UwpSCPnNPksM1meQJnBAF',
          id: '0UwpSCPnNPksM1meQJnBAF',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273842e732b778998eef17b405f',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02842e732b778998eef17b405f',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851842e732b778998eef17b405f',
              width: 64
            }
          ],
          name: 'Rise Of An Empire (Deluxe Edition)',
          release_date: '2014-01-01',
          release_date_precision: 'day',
          total_tracks: 14,
          type: 'album',
          uri: 'spotify:album:0UwpSCPnNPksM1meQJnBAF'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5OrB6Jhhrl9y2PK0pSV4VP'
            },
            href: 'https://api.spotify.com/v1/artists/5OrB6Jhhrl9y2PK0pSV4VP',
            id: '5OrB6Jhhrl9y2PK0pSV4VP',
            name: 'Young Money',
            type: 'artist',
            uri: 'spotify:artist:5OrB6Jhhrl9y2PK0pSV4VP'
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'
            },
            href: 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4',
            id: '3TVXtAsR1Inumwj472S9r4',
            name: 'Drake',
            type: 'artist',
            uri: 'spotify:artist:3TVXtAsR1Inumwj472S9r4'
          }
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 188320,
        explicit: true,
        external_ids: {
          isrc: 'USCM51400038'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/6HfOzLLjsaXsehIFEsrxTk'
        },
        href: 'https://api.spotify.com/v1/tracks/6HfOzLLjsaXsehIFEsrxTk',
        id: '6HfOzLLjsaXsehIFEsrxTk',
        is_local: false,
        name: 'Trophies',
        popularity: 71,
        preview_url: 'https://p.scdn.co/mp3-preview/a4bdbe9767c2867802c2019413df833349bfdbab?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 2,
        type: 'track',
        uri: 'spotify:track:6HfOzLLjsaXsehIFEsrxTk'
      },
      {
        album: {
          album_type: 'SINGLE',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'
              },
              href: 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
              id: '7jVv8c5Fj3E9VhNjxT4snq',
              name: 'Lil Nas X',
              type: 'artist',
              uri: 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/4IRiXE5NROxknUSAUSjMoO'
          },
          href: 'https://api.spotify.com/v1/albums/4IRiXE5NROxknUSAUSjMoO',
          id: '4IRiXE5NROxknUSAUSjMoO',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273c0e7bf5cdd630f314f20586a',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02c0e7bf5cdd630f314f20586a',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851c0e7bf5cdd630f314f20586a',
              width: 64
            }
          ],
          name: '7 EP',
          release_date: '2019-06-21',
          release_date_precision: 'day',
          total_tracks: 8,
          type: 'album',
          uri: 'spotify:album:4IRiXE5NROxknUSAUSjMoO'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7jVv8c5Fj3E9VhNjxT4snq'
            },
            href: 'https://api.spotify.com/v1/artists/7jVv8c5Fj3E9VhNjxT4snq',
            id: '7jVv8c5Fj3E9VhNjxT4snq',
            name: 'Lil Nas X',
            type: 'artist',
            uri: 'spotify:artist:7jVv8c5Fj3E9VhNjxT4snq'
          }
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 113000,
        explicit: false,
        external_ids: {
          isrc: 'USSM11901941'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/0F7FA14euOIX8KcbEturGH'
        },
        href: 'https://api.spotify.com/v1/tracks/0F7FA14euOIX8KcbEturGH',
        id: '0F7FA14euOIX8KcbEturGH',
        is_local: false,
        name: 'Old Town Road',
        popularity: 83,
        preview_url: 'https://p.scdn.co/mp3-preview/eb79f705a57a20599ceaa12d412dda40fc42069d?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 8,
        type: 'track',
        uri: 'spotify:track:0F7FA14euOIX8KcbEturGH'
      },
      {
        album: {
          album_type: 'SINGLE',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop'
              },
              href: 'https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop',
              id: '137W8MRPWKqSmrBGDBFSop',
              name: 'Wiz Khalifa',
              type: 'artist',
              uri: 'spotify:artist:137W8MRPWKqSmrBGDBFSop'
            }
          ],
          available_markets: [
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IT',
            'JP',
            'LT',
            'LU',
            'LV',
            'MT',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'RO',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/5f8dieyt0L9xmvEmBu5IC0'
          },
          href: 'https://api.spotify.com/v1/albums/5f8dieyt0L9xmvEmBu5IC0',
          id: '5f8dieyt0L9xmvEmBu5IC0',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b2730b20eaa56e76c198d62c4beb',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e020b20eaa56e76c198d62c4beb',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d000048510b20eaa56e76c198d62c4beb',
              width: 64
            }
          ],
          name: 'King of Everything',
          release_date: '2015-10-16',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:5f8dieyt0L9xmvEmBu5IC0'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop'
            },
            href: 'https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop',
            id: '137W8MRPWKqSmrBGDBFSop',
            name: 'Wiz Khalifa',
            type: 'artist',
            uri: 'spotify:artist:137W8MRPWKqSmrBGDBFSop'
          }
        ],
        available_markets: [
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'EC',
          'EE',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IT',
          'JP',
          'LT',
          'LU',
          'LV',
          'MT',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'PA',
          'PE',
          'PH',
          'PL',
          'PT',
          'PY',
          'RO',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 222179,
        explicit: true,
        external_ids: {
          isrc: 'USAT21503607'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/1rZah1UGXvgiQCqLVlq4hS'
        },
        href: 'https://api.spotify.com/v1/tracks/1rZah1UGXvgiQCqLVlq4hS',
        id: '1rZah1UGXvgiQCqLVlq4hS',
        is_local: false,
        name: 'King of Everything',
        popularity: 60,
        preview_url: 'https://p.scdn.co/mp3-preview/bcc37dc95772fc70b055d3cc0b4269158e057964?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:1rZah1UGXvgiQCqLVlq4hS'
      },
      {
        album: {
          album_type: 'SINGLE',
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/7c0XG5cIJTrrAgEC3ULPiq'
              },
              href: 'https://api.spotify.com/v1/artists/7c0XG5cIJTrrAgEC3ULPiq',
              id: '7c0XG5cIJTrrAgEC3ULPiq',
              name: 'Ty Dolla $ign',
              type: 'artist',
              uri: 'spotify:artist:7c0XG5cIJTrrAgEC3ULPiq'
            }
          ],
          available_markets: [
            'AD',
            'AE',
            'AR',
            'AT',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/3SHx7bBQFI4J8QRr6D5cOK'
          },
          href: 'https://api.spotify.com/v1/albums/3SHx7bBQFI4J8QRr6D5cOK',
          id: '3SHx7bBQFI4J8QRr6D5cOK',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b2731c04efd2804b16cf689de7f0',
              width: 640
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e021c04efd2804b16cf689de7f0',
              width: 300
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d000048511c04efd2804b16cf689de7f0',
              width: 64
            }
          ],
          name: 'Or Nah (feat. The Weeknd, Wiz Khalifa & DJ Mustard) [Remix]',
          release_date: '2014-06-10',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:3SHx7bBQFI4J8QRr6D5cOK'
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/7c0XG5cIJTrrAgEC3ULPiq'
            },
            href: 'https://api.spotify.com/v1/artists/7c0XG5cIJTrrAgEC3ULPiq',
            id: '7c0XG5cIJTrrAgEC3ULPiq',
            name: 'Ty Dolla $ign',
            type: 'artist',
            uri: 'spotify:artist:7c0XG5cIJTrrAgEC3ULPiq'
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ'
            },
            href: 'https://api.spotify.com/v1/artists/1Xyo4u8uXC1ZmMpatF05PJ',
            id: '1Xyo4u8uXC1ZmMpatF05PJ',
            name: 'The Weeknd',
            type: 'artist',
            uri: 'spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ'
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/137W8MRPWKqSmrBGDBFSop'
            },
            href: 'https://api.spotify.com/v1/artists/137W8MRPWKqSmrBGDBFSop',
            id: '137W8MRPWKqSmrBGDBFSop',
            name: 'Wiz Khalifa',
            type: 'artist',
            uri: 'spotify:artist:137W8MRPWKqSmrBGDBFSop'
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0YinUQ50QDB7ZxSCLyQ40k'
            },
            href: 'https://api.spotify.com/v1/artists/0YinUQ50QDB7ZxSCLyQ40k',
            id: '0YinUQ50QDB7ZxSCLyQ40k',
            name: 'Mustard',
            type: 'artist',
            uri: 'spotify:artist:0YinUQ50QDB7ZxSCLyQ40k'
          }
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA'
        ],
        disc_number: 1,
        duration_ms: 242983,
        explicit: true,
        external_ids: {
          isrc: 'USAT21401391'
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/7t2bFihaDvhIrd2gn2CWJO'
        },
        href: 'https://api.spotify.com/v1/tracks/7t2bFihaDvhIrd2gn2CWJO',
        id: '7t2bFihaDvhIrd2gn2CWJO',
        is_local: false,
        name: 'Or Nah (feat. The Weeknd, Wiz Khalifa & DJ Mustard) - Remix',
        popularity: 78,
        preview_url: 'https://p.scdn.co/mp3-preview/70f126c139847335bc03c756c55b80c99892268e?cid=774b29d4f13844c495f206cafdad9c86',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:7t2bFihaDvhIrd2gn2CWJO'
      }
    ],
    total: 50,
    limit: 10,
    offset: 5,
    previous: null,
    href: 'https://api.spotify.com/v1/me/top/tracks?limit=10&offset=5',
    next: 'https://api.spotify.com/v1/me/top/tracks?limit=10&offset=15'
  }

const getArtists = async () => {
    return artistsData;
}

const getTracks = async () => {
    return tracksData;
}

module.exports = {
    getArtists,
    getTracks
}